#!/bin/bash

# Source guard
[[ -n "${_BASH_SCRIPTING_UTILS_TIME}" ]] && return; readonly _BASH_SCRIPTING_UTILS_TIME=1

source "${BASH_SOURCE%/*}/logging"

# ------ PUBLIC (USE DIRECTLY IN YOUR SCRIPTS) ------ #

# GET THE CURRENT TIME IN MILLISECONDS

get_time_ms()
{
    echo $(($(date +%s%N)/1000000))
}

# LOG THE ELAPSED TIME IN SECONDS

log_elapsed_time_s()
{
    local start_time_ms="${1}"
    local end_time_ms="${2}"

    info "elapsed: $(echo "scale=3;(${end_time_ms} - ${start_time_ms})/(1*10^03)" | bc) seconds"
}

